name: Taplo validation tags

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: wget
      uses: wei/wget@v1
      with:
        args: https://github.com/tamasfe/taplo/releases/latest/download/taplo-x86_64-unknown-linux-gnu.tar.gz
    - name: execute taplo check
      run: |
        tar -xf taplo-x86_64-unknown-linux-gnu.tar.gz
        ./taplo check src/*/*
